# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-reloader
  description: This component installs the [Stakater Reloader](https://github
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
